apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true

  # CloudNativePG Operator (via Helm)
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.27.0
    helm:
      releaseName: cnpg
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

  # Redis (via Helm)
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: redis
    targetRevision: 24.1.0
    helm:
      parameters:
        - name: architecture
          value: standalone
        - name: master.persistence.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: immich

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

  # Contour (via Git Directory)
  source:
    repoURL: https://github.com/thesmartai/CSP.git
    targetRevision: argo_cd
    path: argo_cd/pre-built
  destination:
    server: https://kubernetes.default.svc
    namespace: projectcontour