apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce # ReadWriteOncePod
  hostPath: # rather network ressource (AWS-Bucket...) than storage on the Cluster
    path: "/mnt/data"
