# Kubernetes Secret für Immich-Datenbankzugang, muss jedoch von GitHub Actions verarbeitet werden, da ansonsten die eigene Syntax nicht erkannt wird
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-app
type: Opaque
stringData:
  username: "${{ secrets.IMMICH_DB_APP_USER }}"
  password: "${{ secrets.IMMICH_DB_APP_PASSWORD }}"