# Helm-Values für das Immich-Deploymend

controllers:
  main:
    containers:
      main:
        image:
          # Image-Tag ist fest gepinnt, verhindert unerwartete Updates durch "latest".
          tag: v2.3.1
        env:
          DB_HOSTNAME: immich-database-rw
          DB_PORT: "5432"
          DB_USERNAME: immich
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-db-app
                key: password
          DB_DATABASE_NAME: immich
          REDIS_HOSTNAME: redis-master
          REDIS_PORT: "6379"
          REDIS_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: redis
                key: redis-password

        resources:
          requests:
            cpu: 100m
            memory: 512Mi
            # Ephemeral Storage sichert lokalen Temp-Speicher (Upload-Buffer...)
            ephemeral-storage: 1Gi
          limits:
            cpu: 1000m
            memory: 4Gi
            ephemeral-storage: 2Gi

immich:
  metrics:
    # Aktiviert den Prometheus ServiceMonitor
    enabled: true
    serviceMonitor:
      enabled: true

  persistence:
    library:
      # Bindet den extern erstellten PVC ein
      # Das Chart kann keinen PVC selbst erstellen, der PVC muss vorab vorhanden sein.
      existingClaim: task-pv-claim

  # Anwendungsconfig mit Standardwerten
  configuration: {}

# Valkey ist deaktiviert, da separat Redis genutzt wird.
valkey:
  enabled: false
