# This file is pre-built from the Grafana Loki Helm chart v6.0.0
# Generated to avoid large Helm chart size issues
# Source: helm template loki grafana/loki --repo https://grafana.github.io/helm-charts --version 6.0.0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: "3.0.0"
    helm.sh/chart: loki-6.0.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: "3.0.0"
    helm.sh/chart: loki-6.0.0
data:
  config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      log_level: info
    
    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: "3.0.0"
    helm.sh/chart: loki-6.0.0
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 3100
    targetPort: http-metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: loki

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: "3.0.0"
    helm.sh/chart: loki-6.0.0
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  serviceName: loki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/version: "3.0.0"
        helm.sh/chart: loki-6.0.0
    spec:
      serviceAccountName: loki
      containers:
      - name: loki
        image: grafana/loki:3.0.0
        imagePullPolicy: IfNotPresent
        args:
        - "-config.file=/etc/loki/config.yaml"
        ports:
        - name: http-metrics
          containerPort: 3100
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /loki
      volumes:
      - name: config
        configMap:
          name: loki
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
