apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    # GEÄNDERT: Kapazität auf 50Gi erhöht, um dem neuen PVC-Request zu entsprechen.
    storage: 50Gi
  accessModes:
    - ReadWriteOnce # ReadWriteOncePod
  hostPath: # rather network ressource (AWS-Bucket...) than storage on the Cluster
    path: "/mnt/data"