apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # GEÄNDERT: Speicheranforderung von 3Gi auf 50Gi erhöht.
      storage: 50Gi